### ISSUE TITLE
Use Simpler GitHub Pages publishing?

### ISSUE THREAD

**Issue by bwtakacy** [ossc-db/dblink_plus#2]
See the GitHub announce https://github.com/blog/2228-simpler-github-pages-publishing and the discussion in https://github.com/ossc-db/pg_rman/issues/36.

How do you think, @kfuru ?

**Comment by kfuru** [comment]
To become it is not necessary to duplicate manage documents, this is a good feature.
To use this feature, Can I try it?

**Comment by bwtakacy** [comment]
Yeah!
Of, course :smile:

**Comment by kfuru** [comment]
I tried it in dblink_plus and syncdb.
How about this?

**Comment by bwtakacy** [comment]
Nice!

It works fine as before 👍 
Thank you for taking a time for this.
